---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: dod31ambtcInEh8k8kOJxgLzRkliqkKp7aNytasPGDmwFfuxXwfUl+ahBvQBAjMi2kX6LlAvORxjT1v+9tpv000bT/NaeokI3nYR20YnJL5uyQK5IIxn0ExlJEO9Di1cpEldYRWxEm4XS4OKZehFSlkJGfR6cGjfq3SEEZ1P1Mk5d4KxQYE4631iNn0natEMmmI0d5PJpqN8P8UBvO4u3EATaUCwlIdJC/zCHcHsea1NPHjikZT4hMQY8989ZLJFC/k0YaZo00nSIxlRf/DN+h0y6//N3QTLWVUbyuDdH61er3IGrakAVkzLZG02JfSVLtdSb4jKJzoOcu9lpeN0ENuqaF/rkop5YD6azQRsze950v3MNhSFmhzptOYn4Bicqrw3RPZSIvH0b+nQvHrhBn8Fuh0LyRiAVUlWbSn7DK2PFniTTPhB5bQpquU1Al/q6MolxjhDTPaPHL/jtF68m53vSX5ItjQpUi0WRUmWDyYtMFOltacyBe9263MREDX8k7r5R5jywN7wMyEHgW03fOneF0qqU7i6IpMfl/Nt4Fi105VKvwW/e/Jjp9/sddURuF+rnPZGvBMWkj1mTQQRsy3cy4i3VdLJeSd2Xtwg5anzJuhcP9j7A+89dXAgxNlUvOsLAnWzx6+1rxuazwYyly+d49rqzHnRJE3qkQFodH4=
  email: false
